# Generated by Django 4.0.4 on 2022-04-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_task_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(default='media/task_images/q1.png', null=True, upload_to='task_images'),
        ),
    ]
