# Generated by Django 4.0.4 on 2022-05-21 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_quesmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quesmodel',
            options={'verbose_name': 'вопрос', 'verbose_name_plural': 'вопросы'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
    ]
