# Generated by Django 4.0.4 on 2022-05-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_quesmodel_options_alter_task_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Takirip')),
                ('ab_theme', models.TextField(verbose_name='Takirip jaily')),
                ('image', models.ImageField(blank=True, null=True, upload_to='task_images')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
