# Generated by Django 4.0.4 on 2022-05-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_theme_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='quesmodel',
            name='classes',
            field=models.CharField(default='1 synyp', max_length=10, verbose_name='Qay synyp?'),
        ),
    ]
