# Generated by Django 4.0.4 on 2022-05-23 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_newuserform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewUserForm',
        ),
    ]
