# Generated by Django 4.0.4 on 2022-05-23 05:57

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_profile_newuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_Title', models.CharField(max_length=200)),
                ('video', embed_video.fields.EmbedVideoField()),
            ],
            options={
                'verbose_name_plural': 'BeineSabak',
            },
        ),
        migrations.DeleteModel(
            name='NewUser',
        ),
    ]
