# Generated by Django 4.0.4 on 2022-05-23 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_video_delete_newuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={},
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_Title',
        ),
    ]
